"""
commodity_list.py — 35 specific commodities tracked by the daily shortage intelligence module.

Each entry:
  name                 Display name in prompts and dashboard
  sector               High-level category for filtering
  unit                 Physical unit (context in prompts)
  strategic_importance 1 (low) to 5 (critical) — tiebreaker in rankings
  aliases              Search terms for IngestStore article retrieval
  description          One sentence of context embedded in the Mistral prompt
  key_producers        Top 2-3 producers (geopolitical framing)
"""

COMMODITIES: list[dict] = [
    # ── Critical Minerals (7) ──────────────────────────────────────────────────
    {
        "name": "Gallium",
        "sector": "Critical Minerals",
        "unit": "kg",
        "strategic_importance": 5,
        "aliases": ["gallium", "gallium metal", "Ga"],
        "description": "Essential for semiconductors, LEDs, and 5G RF chips; China controls ~98% of refined output and imposed export licensing in 2023.",
        "key_producers": "China (98%), Russia (1%)",
    },
    {
        "name": "Germanium",
        "sector": "Critical Minerals",
        "unit": "kg",
        "strategic_importance": 5,
        "aliases": ["germanium", "GeO2", "germanium dioxide"],
        "description": "Critical for fiber optics, infrared optics, and solar cells; China dominates and imposed export controls in 2023.",
        "key_producers": "China (80%), Russia, Canada",
    },
    {
        "name": "Antimony",
        "sector": "Critical Minerals",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["antimony", "antimony trioxide", "Sb"],
        "description": "Used in flame retardants, grid-scale batteries, and military munitions; China export restrictions tightened in 2024.",
        "key_producers": "China (60%), Tajikistan, Russia",
    },
    {
        "name": "Indium",
        "sector": "Critical Minerals",
        "unit": "kg",
        "strategic_importance": 4,
        "aliases": ["indium", "ITO", "indium tin oxide"],
        "description": "Used in ITO displays and thin-film solar; entirely a byproduct of zinc smelting, no primary mines exist.",
        "key_producers": "China (57%), South Korea, Japan",
    },
    {
        "name": "Rhenium",
        "sector": "Critical Minerals",
        "unit": "kg",
        "strategic_importance": 4,
        "aliases": ["rhenium", "superalloy", "Re"],
        "description": "Critical for jet engine single-crystal superalloys and petroleum catalysts; extremely thin market.",
        "key_producers": "Chile (52%), Poland, Kazakhstan",
    },
    {
        "name": "Hafnium",
        "sector": "Critical Minerals",
        "unit": "kg",
        "strategic_importance": 5,
        "aliases": ["hafnium", "HfO2", "hafnium oxide"],
        "description": "Essential for advanced logic transistor gate dielectrics at 7nm and below; byproduct of zirconium nuclear fuel processing.",
        "key_producers": "France (50%), USA, Russia",
    },
    {
        "name": "Tungsten",
        "sector": "Critical Minerals",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["tungsten", "tungsten carbide", "WC", "wolfram"],
        "description": "Used in cutting tools, defense penetrators, and electronics; China tightening export quotas.",
        "key_producers": "China (84%), Vietnam, Russia",
    },
    # ── Rare Earths (4) ───────────────────────────────────────────────────────
    {
        "name": "Dysprosium",
        "sector": "Rare Earths",
        "unit": "kg",
        "strategic_importance": 5,
        "aliases": ["dysprosium", "heavy rare earth", "HREE", "Dy"],
        "description": "Essential for high-temperature NdFeB permanent magnets in EV motors and wind turbines; China controls heavy rare earth ionic clay deposits.",
        "key_producers": "China (95%)",
    },
    {
        "name": "Terbium",
        "sector": "Rare Earths",
        "unit": "kg",
        "strategic_importance": 5,
        "aliases": ["terbium", "Tb"],
        "description": "Co-dopant in NdFeB magnets and green phosphors; supply almost entirely from Chinese ionic clay deposits.",
        "key_producers": "China (95%)",
    },
    {
        "name": "NdPr",
        "sector": "Rare Earths",
        "unit": "t",
        "strategic_importance": 5,
        "aliases": ["neodymium", "praseodymium", "NdPr", "rare earth magnet", "NdFeB"],
        "description": "Primary feedstock for permanent magnets used in EV motors, robotics, and wind turbines; demand growing faster than new mine supply.",
        "key_producers": "China (85%), Australia (MP Materials), Myanmar",
    },
    {
        "name": "Scandium",
        "sector": "Rare Earths",
        "unit": "kg",
        "strategic_importance": 3,
        "aliases": ["scandium", "Sc", "scandium oxide"],
        "description": "Strengthens aluminum alloys for aerospace; only viable fuel cell SOFC electrolyte material; production is tiny and byproduct-dependent.",
        "key_producers": "China, Russia, Philippines",
    },
    # ── Battery Materials (5) ─────────────────────────────────────────────────
    {
        "name": "Cobalt",
        "sector": "Battery",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["cobalt", "DRC cobalt", "cobalt sulfate", "Co"],
        "description": "Key cathode material in NMC/NCA batteries; 70% from DRC with artisanal mining and supply disruption risk.",
        "key_producers": "DRC (73%), Russia, Australia",
    },
    {
        "name": "Lithium Carbonate",
        "sector": "Battery",
        "unit": "t",
        "strategic_importance": 5,
        "aliases": ["lithium carbonate", "lithium hydroxide", "lithium", "LCE", "Li"],
        "description": "Core lithium battery feedstock; price crashed from 2023 highs due to Chinese oversupply but structural deficit expected post-2026.",
        "key_producers": "Australia (Greenbushes), Chile, China",
    },
    {
        "name": "Graphite (Natural)",
        "sector": "Battery",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["natural graphite", "graphite anode", "spherical graphite", "graphite"],
        "description": "Dominant anode material for lithium-ion batteries; China controls 90% of refined supply and imposed export licensing in 2023.",
        "key_producers": "China (90%), Mozambique, Madagascar",
    },
    {
        "name": "Manganese Sulphate",
        "sector": "Battery",
        "unit": "t",
        "strategic_importance": 3,
        "aliases": ["manganese sulphate", "manganese sulfate", "HPMSM", "high purity manganese", "manganese"],
        "description": "Cathode precursor for LMFP and NMC chemistries; high-purity processing almost entirely in China.",
        "key_producers": "South Africa (ore), China (processing)",
    },
    {
        "name": "Nickel Sulphate",
        "sector": "Battery",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["nickel sulphate", "nickel sulfate", "battery nickel", "Class I nickel", "nickel"],
        "description": "High-purity nickel for NMC cathodes; Indonesian HPAL supply surge creating mixed-class surplus despite Class I battery-grade deficit.",
        "key_producers": "Indonesia, Philippines, Russia",
    },
    # ── Semiconductor Materials (5) ───────────────────────────────────────────
    {
        "name": "High Purity Quartz",
        "sector": "Semiconductor",
        "unit": "t",
        "strategic_importance": 5,
        "aliases": ["high purity quartz", "HPQ", "quartz crucible", "fused silica", "Spruce Pine"],
        "description": "Ultra-pure quartz crucibles are consumables in silicon crystal growth for all wafers; single mine in Spruce Pine NC is a single point of failure.",
        "key_producers": "USA (Spruce Pine NC), Norway, China",
    },
    {
        "name": "Silicon Metal",
        "sector": "Semiconductor",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["silicon metal", "polysilicon", "semiconductor silicon", "Si metal"],
        "description": "Feedstock for semiconductor-grade polysilicon and solar wafers; energy-intensive smelting makes European supply uneconomic.",
        "key_producers": "China (70%), Norway, Brazil",
    },
    {
        "name": "Neon",
        "sector": "Semiconductor",
        "unit": "m3",
        "strategic_importance": 5,
        "aliases": ["neon gas", "high purity neon", "neon", "semiconductor gas"],
        "description": "Used in ArF excimer lasers for DUV lithography; Ukraine supplied 45-54% of global semiconductor-grade neon before 2022 war.",
        "key_producers": "USA, China (growing), Ukraine (historical)",
    },
    {
        "name": "Palladium",
        "sector": "Semiconductor",
        "unit": "troy oz",
        "strategic_importance": 4,
        "aliases": ["palladium", "PGM", "platinum group metal", "Pd"],
        "description": "Used in multi-layer ceramic capacitors (MLCCs), catalytic converters, and hydrogen sensors; Russia controls 40% of global supply.",
        "key_producers": "Russia (40%), South Africa (38%), Canada",
    },
    {
        "name": "Hydrofluoric Acid",
        "sector": "Semiconductor",
        "unit": "t",
        "strategic_importance": 5,
        "aliases": ["hydrofluoric acid", "HF acid", "hydrogen fluoride", "HF", "etch chemical"],
        "description": "Critical semiconductor etching chemical with no substitute; ultra-high-purity supply concentrated in Japan (Stella Chemifa, Morita Chemical).",
        "key_producers": "Japan (Stella Chemifa, Morita), South Korea",
    },
    # ── Base Metals (4) ───────────────────────────────────────────────────────
    {
        "name": "Copper",
        "sector": "Base Metals",
        "unit": "t",
        "strategic_importance": 5,
        "aliases": ["copper", "copper concentrate", "COMEX copper", "copper cathode", "Cu"],
        "description": "Critical for grid electrification, AI data center power, and EV charging; new mines take 15-20 years to permit and build.",
        "key_producers": "Chile (27%), Peru (12%), DR Congo (10%)",
    },
    {
        "name": "Zinc Concentrate",
        "sector": "Base Metals",
        "unit": "t",
        "strategic_importance": 3,
        "aliases": ["zinc concentrate", "zinc", "zinc smelter", "Zn"],
        "description": "Anti-corrosion steel coating and galvanizing; European smelters shut under high energy costs, tightening refined supply.",
        "key_producers": "China (34%), Peru, Australia",
    },
    {
        "name": "Alumina",
        "sector": "Base Metals",
        "unit": "t",
        "strategic_importance": 3,
        "aliases": ["alumina", "aluminum oxide", "bauxite", "Al2O3", "aluminium oxide"],
        "description": "Intermediate aluminum feedstock; Guinea disruption and Australian refinery costs create periodic tightness.",
        "key_producers": "Australia (22%), China (20%), Brazil, Guinea",
    },
    {
        "name": "Fluorspar",
        "sector": "Base Metals",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["fluorspar", "fluorite", "CaF2", "acid spar", "fluorite ore"],
        "description": "Feedstock for hydrofluoric acid, refrigerants, and lithium hexafluorophosphate battery electrolyte; China controls 65% of output.",
        "key_producers": "China (65%), Mexico, South Africa",
    },
    # ── Energy / Industrial (4) ───────────────────────────────────────────────
    {
        "name": "Uranium",
        "sector": "Energy/Industrial",
        "unit": "lb U3O8",
        "strategic_importance": 5,
        "aliases": ["uranium", "U3O8", "yellowcake", "uranium oxide", "nuclear fuel"],
        "description": "Nuclear power fuel; Western utilities under-contracted after years of low prices; Kazakh supply and Niger coup affect availability.",
        "key_producers": "Kazakhstan (45%), Canada (Cigar Lake), Namibia",
    },
    {
        "name": "LNG",
        "sector": "Energy/Industrial",
        "unit": "MMBtu",
        "strategic_importance": 4,
        "aliases": ["LNG", "liquefied natural gas", "natural gas", "LNG terminal", "LNG tanker"],
        "description": "Liquefied natural gas for European power and Asian industry; structural deficit as new liquefaction capacity won't arrive until 2026-2027.",
        "key_producers": "USA (40% of exports), Qatar, Australia",
    },
    {
        "name": "Metallurgical Coal",
        "sector": "Energy/Industrial",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["metallurgical coal", "coking coal", "met coal", "hard coking coal", "HCC"],
        "description": "Irreplaceable blast furnace feedstock for steel; Australian Queensland floods periodically wipe out 15% of global supply.",
        "key_producers": "Australia (60%), USA, Russia",
    },
    {
        "name": "Helium",
        "sector": "Energy/Industrial",
        "unit": "mcf",
        "strategic_importance": 4,
        "aliases": ["helium", "helium supply", "liquid helium", "He"],
        "description": "MRI machines, semiconductor fab cooling, fiber optics manufacturing; non-renewable, escapes atmosphere, no substitute.",
        "key_producers": "USA (BLM Federal Reserve, ExxonMobil WY), Qatar, Russia",
    },
    # ── Fertilizers (4) ───────────────────────────────────────────────────────
    {
        "name": "Potash",
        "sector": "Fertilizer",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["potash", "MOP", "muriate of potash", "KCl", "potassium chloride"],
        "description": "Core potassium fertilizer; Russia and Belarus combined control 40% of global export capacity; sanctions constrain supply.",
        "key_producers": "Canada (Nutrien, Mosaic), Russia, Belarus",
    },
    {
        "name": "Phosphate Rock",
        "sector": "Fertilizer",
        "unit": "t",
        "strategic_importance": 4,
        "aliases": ["phosphate rock", "phosphate", "phosphoric acid", "DAP", "MAP"],
        "description": "Non-substitutable fertilizer feedstock; Morocco and Western Sahara control 70% of global reserves; finite resource.",
        "key_producers": "Morocco/W.Sahara (70%), China (export-restricting), Russia",
    },
    {
        "name": "Urea",
        "sector": "Fertilizer",
        "unit": "t",
        "strategic_importance": 3,
        "aliases": ["urea", "nitrogen fertilizer", "urea price", "ammonia", "AN fertilizer"],
        "description": "Dominant nitrogen fertilizer; natural gas price-linked production cost; Chinese export restrictions applied during domestic shortage.",
        "key_producers": "China (30%), Russia, Middle East (gas-advantaged)",
    },
    {
        "name": "Sulfur",
        "sector": "Fertilizer",
        "unit": "t",
        "strategic_importance": 3,
        "aliases": ["sulfur", "sulphur", "elemental sulfur", "sulfuric acid"],
        "description": "Sulfuric acid feedstock for phosphate fertilizers; entirely a refinery and gas-plant byproduct — supply cannot be independently increased.",
        "key_producers": "Saudi Arabia (Aramco), Russia, Canada (oil sands)",
    },
    # ── Food Commodities (2) ──────────────────────────────────────────────────
    {
        "name": "Cocoa",
        "sector": "Food",
        "unit": "t",
        "strategic_importance": 2,
        "aliases": ["cocoa", "cacao", "cocoa butter", "cocoa beans", "chocolate"],
        "description": "Chocolate and confectionery feedstock; West Africa supply shock from El Nino drought and cocoa swollen shoot virus destroyed 40% of Ghanaian crop.",
        "key_producers": "Ivory Coast (45%), Ghana (17%), Ecuador",
    },
    {
        "name": "Robusta Coffee",
        "sector": "Food",
        "unit": "bags",
        "strategic_importance": 2,
        "aliases": ["robusta coffee", "coffee robusta", "coffee futures", "robusta", "Vietnam coffee"],
        "description": "Lower-grade coffee used in instant blends and espresso; Vietnam drought and La Nina weather cycle compressed supply in 2024-2025.",
        "key_producers": "Vietnam (40%), Brazil, Indonesia",
    },
]
